### ISSUE TITLE
Writer needs an .into_inner() function

### ISSUE THREAD

**Issue by surferjeff** [image-rs/image-png#298]
I want to write a PNG to memory.  I wrote code like this:

```rs
    let mut encoder = png::Encoder::new(Cursor::new(Vec::new()), info.width, info.height);
    encoder.set_color(png::ColorType::RGB);
    encoder.set_depth(info.bit_depth);
    let mut writer = encoder.write_header()?;
    writer.write_image_data(&frame)?;
    let cursor = writer.into_inner();
    let bytes = cursor.into_inner();
```

I can't get the bytes back out without an `into_inner()` function.  The line  let `cursor = writer.into_inner();` fails to compile because there's no `.into_inner()` function.

**Comment by fintelia** [comment]
Couldn't you do:
```rust
let mut bytes = Vec::new();
{
    let mut encoder = png::Encoder::new(Cursor::new(&mut bytes), info.width, info.height);
    encoder.set_color(png::ColorType::RGB);
    encoder.set_depth(info.bit_depth);
    let mut writer = encoder.write_header()?;
    writer.write_image_data(&frame)?;
}

**Comment by surferjeff** [comment]
Yes, that worked.  Thanks!

**Comment by ravenexp** [comment]
> Couldn't you do:
> 
> ```rust
> let mut bytes = Vec::new();
> {
>     let mut encoder = png::Encoder::new(Cursor::new(&mut bytes), info.width, info.height);
>     encoder.set_color(png::ColorType::RGB);
>     encoder.set_depth(info.bit_depth);
>     let mut writer = encoder.write_header()?;
>     writer.write_image_data(&frame)?;
> }
> ```

This workaround no longer works in `0.17`:

```
error[E0597]: `pngbuf` does not live long enough
  --> src/png.rs:31:52
   |
31 |         let mut encoder = Encoder::new(Cursor::new(&mut pngbuf), self.width, self.height);
   |                                        ------------^^^^^^^^^^^-
   |                                        |           |
   |                                        |           borrowed value does not live long enough
   |                                        argument requires that `pngbuf` is borrowed for `'static`
...
50 |     }
   |     - `pngbuf` dropped here while still borrowed
```

I believe this is because `Encoder::new()` now enforces a `'static` lifetime parameter for some reason:

https://github.com/image-rs/image-png/blob/c24fc93134ce82579595912230f9a3aed33bb1fc/src/encoder.rs#L173-L174

I think this issue should be reopened for version 0.17 and #299 may be revived as well.

**Comment by fintelia** [comment]
Could you check why the static bound was added? Might be that we could remove that instead

**Comment by ravenexp** [comment]
It was added in https://github.com/image-rs/image-png/commit/7ed5169f56d3224a84f01a0309cddbef25844903

I don't understand the motivation behind it well though...

**Comment by fintelia** [comment]
I don't quite understand that either, but it looks like the static bound isn't meant to apply to the writer at all!

**Comment by HeroicKatora** [comment]
It still works: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=769e84f77aae22624b26ec51df1a74c1

The return value does not force `W: 'static`. Can you link to full code?

**Comment by ravenexp** [comment]
I believe Rust Playground imports `png` version `0.16`. The API I'm using in `0.17` is not there:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=037ccad055f3d5f8862707dacfbdd41a

**Comment by HeroicKatora** [comment]
Okay, that's a separate problem for `StreamWriter` then. As a workaround you can use `stream_writer` instead of `into_stream_writer`. This requires you to keep the underlying `Writer` alive and borrow from it like so:

```rust
            let mut writer = encoder
                .write_header()?;
            let mut writer = writer
                .stream_writer()?;

```

So it only works as long as you do not want to store the `StreamWriter` into a `'static` struct itself but then the lifetimes work out. It seems that the requirement `W: 'static` is actually introduced implicitly as part of the _`StreamWriter`_ type:

Specifically in this enum: https://github.com/image-rs/image-png/blob/c24fc93134ce82579595912230f9a3aed33bb1fc/src/encoder.rs#L981-L984

This links the lifetime parameter to the `Writer` and the output type of `into_stream_writer()` is `StreamWriter<'static, W>`. This does not apply to the `Writer::new` constructor because the type `Encoder` has no such link, its lifetime parameter is only used for an `&'a Info` structure and later lost when converting to `Writer` in `writer_header`.

**Comment by ravenexp** [comment]
Thanks!

> Okay, that's a separate problem for `StreamWriter` then. As a workaround you can use `stream_writer` instead of `into_stream_writer`. This requires you to keep the underlying `Writer` alive and borrow from it like so:
> 
> ```rust
>             let mut writer = encoder
>                 .write_header()?;
>             let mut writer = writer
>                 .stream_writer()?;
> ```

worked for me.

I'd happily avoid using `StreamWriter` if there was an easy way to pass 16-bit samples directly to `Writer`.
I also had to google to find out what sample data endianness PNG files use internally.
Ideally, such file format details should not leak through the high level library interface...
